# Generated by Django 5.0.6 on 2024-08-09 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=1997)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IPWhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('link_to_admissions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('birthday', models.DateField(default='unknown')),
                ('graduate_year', models.IntegerField(default=2020)),
                ('school', models.CharField(default='unknown', max_length=500)),
                ('class_number', models.CharField(default='A', max_length=10)),
                ('notes', models.CharField(default='', max_length=10, null=True)),
                ('major', models.CharField(default='Biology', max_length=30)),
                ('location', models.CharField(default='Turkmenistan', max_length=300)),
                ('education_info', models.TextField(default='None')),
                ('current_job', models.TextField(default='None')),
                ('GBT', models.IntegerField(default='0')),
                ('interaction_status', models.IntegerField(default='0')),
                ('description', models.TextField(default='No description available')),
                ('military_status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('future', 'Future')], default='future', max_length=20)),
                ('city', models.CharField(default='Los Angeles', max_length=25)),
                ('marital_status', models.CharField(choices=[('not married', 'Not Married'), ('married', 'Married'), ('divorced', 'Divorced')], default='not married', max_length=20)),
                ('alumni_collection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='alumni.alumnicollection')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_groups', to='alumni.school')),
            ],
        ),
        migrations.AddField(
            model_name='alumnicollection',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_collections', to='alumni.school'),
        ),
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_records', to='alumni.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.BooleanField(default=True)),
                ('show_school', models.BooleanField(default=False)),
                ('show_graduate_year', models.BooleanField(default=True)),
                ('show_birthday', models.BooleanField(default=False)),
                ('show_socials', models.BooleanField(default=False)),
                ('show_location', models.BooleanField(default=False)),
                ('show_education', models.BooleanField(default=False)),
                ('show_current_job', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('show_military', models.BooleanField(default=False)),
                ('show_marital', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
