# Generated by Django 3.2.7 on 2023-09-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_basecalendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseCalendarEvent',
        ),
    ]
